services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - intics

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      intics:
        ipv4_address: 172.20.0.25

#  streamlit:
#    image: python:3.9
#    container_name: streamlit
#    depends_on:
#      - kafka
#    ports:
#      - "8501:8501"
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: >
#      sh -c "pip install streamlit kafka-python && 
#      streamlit run kafka_ui.py"
#    networks:
#      - intics
#
#  api:
#    image: python:3.9
#    container_name: kafka-api
#    depends_on:
#      - kafka
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: >
#      sh -c "pip install flask kafka-python flask-cors && 
#      python kafka_api.py"
#    networks:
#      - intics

networks:
  intics:
    name: pr1.intics
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
